import React from "react";
import { useParams } from "react-router-dom";
import Navbar from "../Navbar";
import Footer from "../Footer";
import BlogContainer from "./BlogContainer";

function Singlepost() {
  const { id } = useParams();

  const blogPosts = [
    {
      id: 1,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 2,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 3,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 4,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 5,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 5,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 7,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 8,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
    {
      id: 9,
      imgLink:
        "https://cdn.britannica.com/25/222725-050-170F622A/Indian-cricketer-Mahendra-Singh-Dhoni-2011.jpg",
      title: "Mahendra Sing Dhoni",
      content:
        "Welcome to Speedcheck, your trusted partner in ensuring seamless connectivity through our comprehensive suite of internet speed check solutions. At Speedcheck, we understand the critical role that internet speed plays in today's technology-driven world. That's why we're committed to providing users like you with accurate and reliable speed check tests, empowering you to stay informed and in control of your online experience. With Speedcheck, conducting a thorough speed check test has never been easier. Whether you're assessing your broadband speed, website performance, wifi connectivity, or network efficiency, our advanced tools deliver precise results in a matter of seconds. Our website speed checker enables you to evaluate the loading times and responsiveness of your online platforms, helping you identify areas for optimization and enhancement. Moreover, our wifi speed check and network speed check tools offer insights into the strength and stability of your wireless connections, ensuring uninterrupted browsing, streaming, and gaming experiences. We understand that download speed is a crucial factor for many users, which is why our download speed checker is designed to provide accurate measurements, allowing you to gauge the efficiency of your data transfer rates. At Speedcheck, we prioritize user convenience and satisfaction. Our intuitive interface and user-friendly design make it effortless to initiate and interpret speed check tests, even for those with limited technical expertise. Furthermore, our commitment to transparency means that you can trust the results of our internet speed checker online, knowing that they reflect the true state of your connection. In addition to our comprehensive speed check services, Speedcheck also serves as a reliable source of information and insights in the ever-evolving landscape of technology and communication. Our regularly updated blogs cover a wide range of topics, from the latest trends in internet speed optimization to in-depth guides on improving network performance. Experience the difference with Speedcheck today and unlock the full potential of your internet connection. Whether you're a casual user seeking reassurance or a tech enthusiast striving for peak performance, Speedcheck is here to support you every step of the way. Join our community of satisfied users and elevate your online experience with Speedcheck.",
    },
  ];

  // Find the blog post with the matching ID
  const blogPost = blogPosts.find((post) => post.id === parseInt(id));

  // If no blog post is found, display a message
  if (!blogPost) {
    return <div>Blog post not found</div>;
  }

  return (
    <div>
      <Navbar />
      <div className="p-2">
      <div className="w-full md:w-[800px] shadow-lg mx-auto my-10 p-4 border border-slate-800 rounded-lg">
        <div className="w-full h-[400px] md:h-[600px]">
          <img
            src={blogPost.imgLink}
            alt="images"
            className="w-full rounded-md h-full"
          />
        </div>
        <div className="w-full">
          <h2 className="text-slate-800 p-3 text-[25px] md:text-[40px] font-[700]">
            {blogPost.title}
          </h2>
          <p className="text-slate-800 p-3 text-sm font-[300] leading-7">
            {blogPost.content}
          </p>
        </div>
      </div>
      </div>
        {/* Display related blogs */}
        <h3 className="text-[25px] md:text-[35px] font-semibold text-center">Related Blogs</h3>
      <div className="w-full md:w-[1100px] grid grid-cols-1 md:grid-cols-2 gap-y-4 gap-x-10  mx-auto my-10 p-4 rounded-lg">
        <BlogContainer visibleCount={4} currentBlogId={parseInt(id)} />
      </div>
      <Footer />
    </div>
  );
}

export default Singlepost;
